language: r
r: 
  - bioc-devel
  - bioc-release
# warnings_are_errors: true
sudo: false
cache: packages

r_packages:
  - covr
  - RSQLite
  - data.table
  - fastmatch
  - ggplot2
  - gridExtra
  - testthat
  - knitr
  - rmarkdown
  - parallel

os:
  - linux
  - osx

bioc_required: true
bioc_packages:
  - BiocCheck
  - BiocParallel
  - reactome.db
  - org.Mm.eg.db

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# see https://github.com/travis-ci/travis-ci/issues/6587
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo -e 'CXX1X=g++ -std=gnu++11 -g -O2 -fPIC\nCXX11=g++ -std=gnu++11 -g -O2 -fPIC' > ~/.R/Makevars; fi


after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
  - Rscript -e 'covr::codecov()'

# Something happend to osx bioc-devel builds 
matrix:
  exclude:
  - os: osx
    r: bioc-devel
